---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
library(tibble)
library(dplyr)
library(tidyr)
library(cmdstanr)
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
devtools::load_all()
options(mc.cores = parallel::detectCores(), brms.backend = "cmdstanr")
```


```{r}
states <- data.frame(id = factor(c("Low", "High"), levels = c("Low", "High")))
nonref_trans_data <- tribble(~.from, ~.to,
                      "Low", "High", 
                      "High", "Low"
                      )
trans_model <- categorical_transitions(nonref_trans_data, states)

trueIntercepts <- c(-1,-0.5)
tm <- compute_transition_matrix(trans_model, states, trueIntercepts)
tm
emitprob <- c(0.1,0.9)

N_series <- 100
N_time <- 30

init_states <- rep(factor(c("Low","High"), levels = levels(states$id)), length.out = N_series)
states_rect <- matrix(NA_integer_, nrow = N_series, ncol = N_time)
states_rect[, 1] <- as.integer(init_states)
for(s in 1:N_series) {
  for(t in 2:N_time) {
    states_rect[s, t] <- sample(1:nrow(states), prob = tm[states_rect[s, t- 1],], size = 1)
  }
}


series_data <- tidyr::crossing(.serie = 1:N_series, .time = 1:N_time, observed = NA)
for(i in 1:nrow(series_data)) {
  series_data$observed[i] <- rbinom(1, size = 1, prob = emitprob[states_rect[series_data$.serie[i],series_data$.time[i]]])
}
series_data$observed <- as.logical(series_data$observed)


obs_model <- ordered_binary_observations("observed")
init_model <- known_initial_states(init_states)        

hmm <- brmshmmdata(~ 0 + .transition_id, series_data,
                   states_data = states,
                   init_model = init_model,
                   trans_model = trans_model,
                   obs_model = obs_model)

```

```{r}
```

Next step: use `subset` to model multiple types of predicted stuff per timepoint

```{r}
#file.remove(list.files(here::here("temp_data"), pattern = ".stan", full.names = TRUE))
scode <- make_stancode_hmm(hmm)                   
file <- cmdstanr::write_stan_file(scode, dir = here::here("temp_data"))
m <- cmdstan_model(file)
#m <- cmdstan_model(here::here("temp_data/test.stan"))
d <- make_standata_hmm(hmm)
res <- m$sample(d)
res$cmdstan_summary()

```

```{r}
hmmfit <- brmhmm(hmm)
summary(hmmfit)
rstan::summary(hmmfit$brmsfit$fit)$summary
```


```{r}
```
```{r}
shinystan::launch_shinystan(rstan::read_stan_csv(res$output_files()))
```


```{r}
#### Setup ####
library(ggplot2)

P = 80 # persons
J = 60 # trials

#### Monotonic decreasing sim ####
intercept = runif(P, 0.7, 0.95)
slope = runif(P, -0.0075, -0.0025)

prob_true = matrix(NA, nrow=J, ncol=P)
for(j in 1:P){
  prob_true[,j] = intercept[j] + slope[j] * 1:J
}

ID = rep(1:P, each=J)

y= matrix(NA, nrow=J, ncol=P)
for(j in 1:P){
  y[,j] = rbinom(J, 1, prob_true[,j])
}

data.frame(person = ID,
           trial = rep(x = 1:J, times = P),
           y = as.vector(y),
           true_y = as.vector(prob_true)
) |>
  ggplot(aes(x = trial, y = y)) +
    geom_point() +
    geom_line(aes(y = true_y), color = "red") +
    facet_wrap(~person)


#### Sinusoidal sim #####
prob_true = matrix(NA, nrow=J, ncol=P)

for(i in 1:P){
  freq = rnorm(1, 7, 1)
  prob_true[,i] = 0.6+0.3*sin((1:J)/freq)
}

ID = rep(1:P, each=J)

y= matrix(NA, nrow=J, ncol=P)
for(j in 1:P){
  y[,j] = rbinom(J, 1, prob_true[,j])
}

data.frame(person = ID,
           trial = rep(x = 1:J, times = P),
           y = as.vector(y),
           true_y = as.vector(prob_true)
) |>
  ggplot(aes(x = trial, y = y)) +
  geom_point() +
  geom_line(aes(y = true_y), color = "red") +
  facet_wrap(~person)
```

